currency system:
- any: ['src/main/java/nl/daanh/commands/fun/*']

emoji system:
- any: ['src/main/java/nl/daanh/commands/emoji/*']

leveling system:
- any: ['src/main/java/nl/daanh/commands/leveling/*']

music system:
- any: ['src/main/java/nl/daanh/commands/music/*']

personality system:
- any: ['src/main/java/nl/daanh/commands/personality/*']
