fun system:
- src/main/java/nl/daanh/hiromi/commands/fun/*

emoji system:
- src/main/java/nl/daanh/hiromi/commands/emoji/*

leveling system:
- src/main/java/nl/daanh/hiromi/commands/leveling/*

music system:
- src/main/java/nl/daanh/hiromi/commands/music/*

personality system:
- src/main/java/nl/daanh/hiromi/commands/personality/*

datasource:
- src/main/java/nl/daanh/hiromi/database/*

utils:
- src/main/java/nl/daanh/hiromi/utils/*

listeners:
- src/main/java/nl/daanh/hiromi/listeners/*
