services:
  bot:
    build: .
    expose: [ 5005 ]
    ports:
      - 127.0.0.1:8765:8765/tcp
      - 127.0.0.1:8765:8765/udp
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8765 -Djava.security.egd=file:/dev/./urandom -jar /app/bot.jar
    depends_on: [ database, lavalink ]

  lavalink:
    image: fredboat/lavalink:master
    volumes:
      - type: bind
        source: ./lavalink_config.yml
        target: /opt/Lavalink/application.yml
      - type: bind
        source: ./lavalink-plugins
        target: /opt/Lavalink/plugins
    expose: [ 2333 ]

  database:
    image: postgres:14
    ports:
      - 127.0.0.1:8432:5432/tcp
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    expose: [ 5432 ]
    environment:
      POSTGRES_USER: hiromi
      POSTGRES_PASSWORD: hiromi
      POSTGRES_DB: hiromi
