// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: guildmessage.proto

package nl.daanh.hiromi.models.proto;

public final class GuildMessage {
  private GuildMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nl_daanh_hiromi_models_proto_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nl_daanh_hiromi_models_proto_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nl_daanh_hiromi_models_proto_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nl_daanh_hiromi_models_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022guildmessage.proto\022\034nl.daanh.hiromi.mo" +
      "dels.proto\"c\n\007Message\022\020\n\010username\030\001 \001(\t\022" +
      "\020\n\010guild_id\030\002 \001(\t\022\022\n\nchannel_id\030\003 \001(\t\022\017\n" +
      "\007user_id\030\004 \001(\t\022\017\n\007message\030\005 \001(\t\"m\n\010Respo" +
      "nse\022\020\n\010username\030\001 \001(\t\022\020\n\010guild_id\030\002 \001(\t\022" +
      "\022\n\nchannel_id\030\003 \001(\t\022\017\n\007user_id\030\004 \001(\t\022\030\n\020" +
      "response_message\030\005 \001(\tB.\n\034nl.daanh.hirom" +
      "i.models.protoB\014GuildMessageP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_nl_daanh_hiromi_models_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nl_daanh_hiromi_models_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nl_daanh_hiromi_models_proto_Message_descriptor,
        new java.lang.String[] { "Username", "GuildId", "ChannelId", "UserId", "Message", });
    internal_static_nl_daanh_hiromi_models_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nl_daanh_hiromi_models_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nl_daanh_hiromi_models_proto_Response_descriptor,
        new java.lang.String[] { "Username", "GuildId", "ChannelId", "UserId", "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
