// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: guildmessage.proto

package nl.daanh.hiromi.models.proto;

/**
 * Protobuf type {@code nl.daanh.hiromi.models.proto.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nl.daanh.hiromi.models.proto.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  public static final int MENTIONS_FIELD_NUMBER = 6;

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private java.util.List<nl.daanh.hiromi.models.proto.Message.Mention> mentions_;

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                    nl.daanh.hiromi.models.proto.Message.class, nl.daanh.hiromi.models.proto.Message.Builder.class);
  }

  private Message() {
    username_ = "";
    guildId_ = "";
    channelId_ = "";
    userId_ = "";
    message_ = "";
    mentions_ = java.util.Collections.emptyList();
  }

  private Message(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            username_ = bs;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            guildId_ = bs;
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000004;
            channelId_ = bs;
            break;
          }
          case 34: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000008;
            userId_ = bs;
            break;
          }
          case 42: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000010;
            message_ = bs;
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) != 0)) {
              mentions_ = new java.util.ArrayList<nl.daanh.hiromi.models.proto.Message.Mention>();
              mutable_bitField0_ |= 0x00000020;
            }
            mentions_.add(
                    input.readMessage(nl.daanh.hiromi.models.proto.Message.Mention.PARSER, extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) != 0)) {
        mentions_ = java.util.Collections.unmodifiableList(mentions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  private int bitField0_;
  public static final int USERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object username_;
  /**
   * <code>optional string username = 1;</code>
   * @return Whether the username field is set.
   */
  @java.lang.Override
  public boolean hasUsername() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        username_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GUILD_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object guildId_;
  /**
   * <code>optional string guild_id = 2;</code>
   * @return Whether the guildId field is set.
   */
  @java.lang.Override
  public boolean hasGuildId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string guild_id = 2;</code>
   * @return The guildId.
   */
  @java.lang.Override
  public java.lang.String getGuildId() {
    java.lang.Object ref = guildId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        guildId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string guild_id = 2;</code>
   * @return The bytes for guildId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGuildIdBytes() {
    java.lang.Object ref = guildId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      guildId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHANNEL_ID_FIELD_NUMBER = 3;
  private volatile java.lang.Object channelId_;
  /**
   * <code>optional string channel_id = 3;</code>
   * @return Whether the channelId field is set.
   */
  @java.lang.Override
  public boolean hasChannelId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string channel_id = 3;</code>
   * @return The channelId.
   */
  @java.lang.Override
  public java.lang.String getChannelId() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        channelId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string channel_id = 3;</code>
   * @return The bytes for channelId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChannelIdBytes() {
    java.lang.Object ref = channelId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object userId_;
  /**
   * <code>optional string user_id = 4;</code>
   * @return Whether the userId field is set.
   */
  @java.lang.Override
  public boolean hasUserId() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string user_id = 4;</code>
   * @return The userId.
   */
  @java.lang.Override
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string user_id = 4;</code>
   * @return The bytes for userId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 5;
  private volatile java.lang.Object message_;
  /**
   * <code>optional string message = 5;</code>
   * @return Whether the message field is set.
   */
  @java.lang.Override
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional string message = 5;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        message_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string message = 5;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  /**
   * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
   */
  @java.lang.Override
  public java.util.List<nl.daanh.hiromi.models.proto.Message.Mention> getMentionsList() {
    return mentions_;
  }

  /**
   * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends nl.daanh.hiromi.models.proto.Message.MentionOrBuilder>
  getMentionsOrBuilderList() {
    return mentions_;
  }

  /**
   * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
   */
  @java.lang.Override
  public int getMentionsCount() {
    return mentions_.size();
  }

  /**
   * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
   */
  @java.lang.Override
  public nl.daanh.hiromi.models.proto.Message.Mention getMentions(int index) {
    return mentions_.get(index);
  }

  /**
   * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
   */
  @java.lang.Override
  public nl.daanh.hiromi.models.proto.Message.MentionOrBuilder getMentionsOrBuilder(
          int index) {
    return mentions_.get(index);
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
          throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, guildId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, channelId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userId_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, message_);
    }
    for (int i = 0; i < mentions_.size(); i++) {
      output.writeMessage(6, mentions_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, guildId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, channelId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userId_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, message_);
    }
    for (int i = 0; i < mentions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(6, mentions_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof nl.daanh.hiromi.models.proto.Message)) {
      return super.equals(obj);
    }
    nl.daanh.hiromi.models.proto.Message other = (nl.daanh.hiromi.models.proto.Message) obj;

    if (hasUsername() != other.hasUsername()) return false;
    if (hasUsername()) {
      if (!getUsername()
          .equals(other.getUsername())) return false;
    }
    if (hasGuildId() != other.hasGuildId()) return false;
    if (hasGuildId()) {
      if (!getGuildId()
          .equals(other.getGuildId())) return false;
    }
    if (hasChannelId() != other.hasChannelId()) return false;
    if (hasChannelId()) {
      if (!getChannelId()
          .equals(other.getChannelId())) return false;
    }
    if (hasUserId() != other.hasUserId()) return false;
    if (hasUserId()) {
      if (!getUserId()
              .equals(other.getUserId())) return false;
    }
    if (hasMessage() != other.hasMessage()) return false;
    if (hasMessage()) {
      if (!getMessage()
              .equals(other.getMessage())) return false;
    }
    if (!getMentionsList()
            .equals(other.getMentionsList())) return false;
    return unknownFields.equals(other.unknownFields);
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUsername()) {
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
    }
    if (hasGuildId()) {
      hash = (37 * hash) + GUILD_ID_FIELD_NUMBER;
      hash = (53 * hash) + getGuildId().hashCode();
    }
    if (hasChannelId()) {
      hash = (37 * hash) + CHANNEL_ID_FIELD_NUMBER;
      hash = (53 * hash) + getChannelId().hashCode();
    }
    if (hasUserId()) {
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
    }
    if (hasMessage()) {
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
    }
    if (getMentionsCount() > 0) {
      hash = (37 * hash) + MENTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getMentionsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public interface MentionOrBuilder extends
          // @@protoc_insertion_point(interface_extends:nl.daanh.hiromi.models.proto.Message.Mention)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string username = 1;</code>
     *
     * @return Whether the username field is set.
     */
    boolean hasUsername();

    /**
     * <code>optional string username = 1;</code>
     *
     * @return The username.
     */
    java.lang.String getUsername();

    /**
     * <code>optional string username = 1;</code>
     *
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
    getUsernameBytes();

    /**
     * <code>optional string user_id = 2;</code>
     *
     * @return Whether the userId field is set.
     */
    boolean hasUserId();

    /**
     * <code>optional string user_id = 2;</code>
     *
     * @return The userId.
     */
    java.lang.String getUserId();

    /**
     * <code>optional string user_id = 2;</code>
     *
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
    getUserIdBytes();
  }

  /**
   * Protobuf type {@code nl.daanh.hiromi.models.proto.Message.Mention}
   */
  public static final class Mention extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:nl.daanh.hiromi.models.proto.Message.Mention)
          MentionOrBuilder {
    public static final int USERNAME_FIELD_NUMBER = 1;
    public static final int USER_ID_FIELD_NUMBER = 2;
    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<Mention>
            PARSER = new com.google.protobuf.AbstractParser<Mention>() {
      @java.lang.Override
      public Mention parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Mention(input, extensionRegistry);
      }
    };
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:nl.daanh.hiromi.models.proto.Message.Mention)
    private static final nl.daanh.hiromi.models.proto.Message.Mention DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new nl.daanh.hiromi.models.proto.Message.Mention();
    }

    private int bitField0_;
    private volatile java.lang.Object username_;
    private volatile java.lang.Object userId_;
    private byte memoizedIsInitialized = -1;

    // Use Mention.newBuilder() to construct.
    private Mention(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Mention() {
      username_ = "";
      userId_ = "";
    }

    private Mention(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              username_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userId_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_Mention_descriptor;
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(nl.daanh.hiromi.models.proto.Message.Mention prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static nl.daanh.hiromi.models.proto.Message.Mention getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<Mention> parser() {
      return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
      return new Mention();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_Mention_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      nl.daanh.hiromi.models.proto.Message.Mention.class, nl.daanh.hiromi.models.proto.Message.Mention.Builder.class);
    }

    /**
     * <code>optional string username = 1;</code>
     *
     * @return Whether the username field is set.
     */
    @java.lang.Override
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional string username = 1;</code>
     *
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }

    /**
     * <code>optional string username = 1;</code>
     *
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>optional string user_id = 2;</code>
     *
     * @return Whether the userId field is set.
     */
    @java.lang.Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional string user_id = 2;</code>
     *
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      }
    }

    /**
     * <code>optional string user_id = 2;</code>
     *
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof nl.daanh.hiromi.models.proto.Message.Mention)) {
        return super.equals(obj);
      }
      nl.daanh.hiromi.models.proto.Message.Mention other = (nl.daanh.hiromi.models.proto.Message.Mention) obj;

      if (hasUsername() != other.hasUsername()) return false;
      if (hasUsername()) {
        if (!getUsername()
                .equals(other.getUsername())) return false;
      }
      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (!getUserId()
                .equals(other.getUserId())) return false;
      }
      return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUsername()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
      }
      if (hasUserId()) {
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mention> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public nl.daanh.hiromi.models.proto.Message.Mention getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code nl.daanh.hiromi.models.proto.Message.Mention}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:nl.daanh.hiromi.models.proto.Message.Mention)
            nl.daanh.hiromi.models.proto.Message.MentionOrBuilder {
      private int bitField0_;
      private java.lang.Object username_ = "";
      private java.lang.Object userId_ = "";

      // Construct using nl.daanh.hiromi.models.proto.Message.Mention.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_Mention_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_Mention_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        nl.daanh.hiromi.models.proto.Message.Mention.class, nl.daanh.hiromi.models.proto.Message.Mention.Builder.class);
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        username_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_Mention_descriptor;
      }

      @java.lang.Override
      public nl.daanh.hiromi.models.proto.Message.Mention getDefaultInstanceForType() {
        return nl.daanh.hiromi.models.proto.Message.Mention.getDefaultInstance();
      }

      @java.lang.Override
      public nl.daanh.hiromi.models.proto.Message.Mention build() {
        nl.daanh.hiromi.models.proto.Message.Mention result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public nl.daanh.hiromi.models.proto.Message.Mention buildPartial() {
        nl.daanh.hiromi.models.proto.Message.Mention result = new nl.daanh.hiromi.models.proto.Message.Mention(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.username_ = username_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof nl.daanh.hiromi.models.proto.Message.Mention) {
          return mergeFrom((nl.daanh.hiromi.models.proto.Message.Mention) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(nl.daanh.hiromi.models.proto.Message.Mention other) {
        if (other == nl.daanh.hiromi.models.proto.Message.Mention.getDefaultInstance()) return this;
        if (other.hasUsername()) {
          bitField0_ |= 0x00000001;
          username_ = other.username_;
          onChanged();
        }
        if (other.hasUserId()) {
          bitField0_ |= 0x00000002;
          userId_ = other.userId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        nl.daanh.hiromi.models.proto.Message.Mention parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (nl.daanh.hiromi.models.proto.Message.Mention) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      /**
       * <code>optional string username = 1;</code>
       *
       * @return Whether the username field is set.
       */
      public boolean hasUsername() {
        return ((bitField0_ & 0x00000001) != 0);
      }

      /**
       * <code>optional string username = 1;</code>
       *
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>optional string username = 1;</code>
       *
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string username = 1;</code>
       *
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
      getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string username = 1;</code>
       *
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        username_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string username = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        bitField0_ = (bitField0_ & ~0x00000001);
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }

      /**
       * <code>optional string user_id = 2;</code>
       *
       * @return Whether the userId field is set.
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) != 0);
      }

      /**
       * <code>optional string user_id = 2;</code>
       *
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>optional string user_id = 2;</code>
       *
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string user_id = 2;</code>
       *
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
      getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>optional string user_id = 2;</code>
       *
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional string user_id = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:nl.daanh.hiromi.models.proto.Message.Mention)
    }

  }

  public static nl.daanh.hiromi.models.proto.Message parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static nl.daanh.hiromi.models.proto.Message parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.daanh.hiromi.models.proto.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.daanh.hiromi.models.proto.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.daanh.hiromi.models.proto.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static nl.daanh.hiromi.models.proto.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static nl.daanh.hiromi.models.proto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nl.daanh.hiromi.models.proto.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static nl.daanh.hiromi.models.proto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static nl.daanh.hiromi.models.proto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static nl.daanh.hiromi.models.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static nl.daanh.hiromi.models.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(nl.daanh.hiromi.models.proto.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code nl.daanh.hiromi.models.proto.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nl.daanh.hiromi.models.proto.Message)
          nl.daanh.hiromi.models.proto.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      nl.daanh.hiromi.models.proto.Message.class, nl.daanh.hiromi.models.proto.Message.Builder.class);
    }

    // Construct using nl.daanh.hiromi.models.proto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private java.util.List<nl.daanh.hiromi.models.proto.Message.Mention> mentions_ =
            java.util.Collections.emptyList();
    private com.google.protobuf.RepeatedFieldBuilderV3<
            nl.daanh.hiromi.models.proto.Message.Mention, nl.daanh.hiromi.models.proto.Message.Mention.Builder, nl.daanh.hiromi.models.proto.Message.MentionOrBuilder> mentionsBuilder_;

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return nl.daanh.hiromi.models.proto.GuildMessage.internal_static_nl_daanh_hiromi_models_proto_Message_descriptor;
    }

    @java.lang.Override
    public nl.daanh.hiromi.models.proto.Message getDefaultInstanceForType() {
      return nl.daanh.hiromi.models.proto.Message.getDefaultInstance();
    }

    @java.lang.Override
    public nl.daanh.hiromi.models.proto.Message build() {
      nl.daanh.hiromi.models.proto.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMentionsFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof nl.daanh.hiromi.models.proto.Message) {
        return mergeFrom((nl.daanh.hiromi.models.proto.Message) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      username_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      guildId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      channelId_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      userId_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      message_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      if (mentionsBuilder_ == null) {
        mentions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        mentionsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      nl.daanh.hiromi.models.proto.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (nl.daanh.hiromi.models.proto.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object username_ = "";
    /**
     * <code>optional string username = 1;</code>
     * @return Whether the username field is set.
     */
    public boolean hasUsername() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string username = 1;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      bitField0_ = (bitField0_ & ~0x00000001);
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>optional string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object guildId_ = "";
    /**
     * <code>optional string guild_id = 2;</code>
     * @return Whether the guildId field is set.
     */
    public boolean hasGuildId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string guild_id = 2;</code>
     * @return The guildId.
     */
    public java.lang.String getGuildId() {
      java.lang.Object ref = guildId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          guildId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string guild_id = 2;</code>
     * @return The bytes for guildId.
     */
    public com.google.protobuf.ByteString
        getGuildIdBytes() {
      java.lang.Object ref = guildId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guildId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string guild_id = 2;</code>
     * @param value The guildId to set.
     * @return This builder for chaining.
     */
    public Builder setGuildId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      guildId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string guild_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGuildId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      guildId_ = getDefaultInstance().getGuildId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string guild_id = 2;</code>
     * @param value The bytes for guildId to set.
     * @return This builder for chaining.
     */
    public Builder setGuildIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      guildId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object channelId_ = "";
    /**
     * <code>optional string channel_id = 3;</code>
     * @return Whether the channelId field is set.
     */
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string channel_id = 3;</code>
     * @return The channelId.
     */
    public java.lang.String getChannelId() {
      java.lang.Object ref = channelId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          channelId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string channel_id = 3;</code>
     * @return The bytes for channelId.
     */
    public com.google.protobuf.ByteString
        getChannelIdBytes() {
      java.lang.Object ref = channelId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string channel_id = 3;</code>
     * @param value The channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      channelId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string channel_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      channelId_ = getDefaultInstance().getChannelId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string channel_id = 3;</code>
     * @param value The bytes for channelId to set.
     * @return This builder for chaining.
     */
    public Builder setChannelIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      channelId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <code>optional string user_id = 4;</code>
     * @return Whether the userId field is set.
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string user_id = 4;</code>
     * @return The userId.
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string user_id = 4;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string user_id = 4;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string user_id = 4;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>optional string message = 5;</code>
     * @return Whether the message field is set.
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string message = 5;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string message = 5;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string message = 5;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
            java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      message_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>optional string message = 5;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000010);
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }

    /**
     * <code>optional string message = 5;</code>
     *
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
            com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      message_ = value;
      onChanged();
      return this;
    }

    @java.lang.Override
    public nl.daanh.hiromi.models.proto.Message buildPartial() {
      nl.daanh.hiromi.models.proto.Message result = new nl.daanh.hiromi.models.proto.Message(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.username_ = username_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.guildId_ = guildId_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.channelId_ = channelId_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        to_bitField0_ |= 0x00000008;
      }
      result.userId_ = userId_;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.message_ = message_;
      if (mentionsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          mentions_ = java.util.Collections.unmodifiableList(mentions_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.mentions_ = mentions_;
      } else {
        result.mentions_ = mentionsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(nl.daanh.hiromi.models.proto.Message other) {
      if (other == nl.daanh.hiromi.models.proto.Message.getDefaultInstance()) return this;
      if (other.hasUsername()) {
        bitField0_ |= 0x00000001;
        username_ = other.username_;
        onChanged();
      }
      if (other.hasGuildId()) {
        bitField0_ |= 0x00000002;
        guildId_ = other.guildId_;
        onChanged();
      }
      if (other.hasChannelId()) {
        bitField0_ |= 0x00000004;
        channelId_ = other.channelId_;
        onChanged();
      }
      if (other.hasUserId()) {
        bitField0_ |= 0x00000008;
        userId_ = other.userId_;
        onChanged();
      }
      if (other.hasMessage()) {
        bitField0_ |= 0x00000010;
        message_ = other.message_;
        onChanged();
      }
      if (mentionsBuilder_ == null) {
        if (!other.mentions_.isEmpty()) {
          if (mentions_.isEmpty()) {
            mentions_ = other.mentions_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureMentionsIsMutable();
            mentions_.addAll(other.mentions_);
          }
          onChanged();
        }
      } else {
        if (!other.mentions_.isEmpty()) {
          if (mentionsBuilder_.isEmpty()) {
            mentionsBuilder_.dispose();
            mentionsBuilder_ = null;
            mentions_ = other.mentions_;
            bitField0_ = (bitField0_ & ~0x00000020);
            mentionsBuilder_ =
                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                            getMentionsFieldBuilder() : null;
          } else {
            mentionsBuilder_.addAllMessages(other.mentions_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    private void ensureMentionsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        mentions_ = new java.util.ArrayList<nl.daanh.hiromi.models.proto.Message.Mention>(mentions_);
        bitField0_ |= 0x00000020;
      }
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public java.util.List<nl.daanh.hiromi.models.proto.Message.Mention> getMentionsList() {
      if (mentionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mentions_);
      } else {
        return mentionsBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public int getMentionsCount() {
      if (mentionsBuilder_ == null) {
        return mentions_.size();
      } else {
        return mentionsBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public nl.daanh.hiromi.models.proto.Message.Mention getMentions(int index) {
      if (mentionsBuilder_ == null) {
        return mentions_.get(index);
      } else {
        return mentionsBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public Builder setMentions(
            int index, nl.daanh.hiromi.models.proto.Message.Mention value) {
      if (mentionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMentionsIsMutable();
        mentions_.set(index, value);
        onChanged();
      } else {
        mentionsBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public Builder setMentions(
            int index, nl.daanh.hiromi.models.proto.Message.Mention.Builder builderForValue) {
      if (mentionsBuilder_ == null) {
        ensureMentionsIsMutable();
        mentions_.set(index, builderForValue.build());
        onChanged();
      } else {
        mentionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public Builder addMentions(nl.daanh.hiromi.models.proto.Message.Mention value) {
      if (mentionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMentionsIsMutable();
        mentions_.add(value);
        onChanged();
      } else {
        mentionsBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public Builder addMentions(
            int index, nl.daanh.hiromi.models.proto.Message.Mention value) {
      if (mentionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMentionsIsMutable();
        mentions_.add(index, value);
        onChanged();
      } else {
        mentionsBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public Builder addMentions(
            nl.daanh.hiromi.models.proto.Message.Mention.Builder builderForValue) {
      if (mentionsBuilder_ == null) {
        ensureMentionsIsMutable();
        mentions_.add(builderForValue.build());
        onChanged();
      } else {
        mentionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public Builder addMentions(
            int index, nl.daanh.hiromi.models.proto.Message.Mention.Builder builderForValue) {
      if (mentionsBuilder_ == null) {
        ensureMentionsIsMutable();
        mentions_.add(index, builderForValue.build());
        onChanged();
      } else {
        mentionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public Builder addAllMentions(
            java.lang.Iterable<? extends nl.daanh.hiromi.models.proto.Message.Mention> values) {
      if (mentionsBuilder_ == null) {
        ensureMentionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, mentions_);
        onChanged();
      } else {
        mentionsBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public Builder clearMentions() {
      if (mentionsBuilder_ == null) {
        mentions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        mentionsBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public Builder removeMentions(int index) {
      if (mentionsBuilder_ == null) {
        ensureMentionsIsMutable();
        mentions_.remove(index);
        onChanged();
      } else {
        mentionsBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public nl.daanh.hiromi.models.proto.Message.Mention.Builder getMentionsBuilder(
            int index) {
      return getMentionsFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public nl.daanh.hiromi.models.proto.Message.MentionOrBuilder getMentionsOrBuilder(
            int index) {
      if (mentionsBuilder_ == null) {
        return mentions_.get(index);
      } else {
        return mentionsBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public java.util.List<? extends nl.daanh.hiromi.models.proto.Message.MentionOrBuilder>
    getMentionsOrBuilderList() {
      if (mentionsBuilder_ != null) {
        return mentionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mentions_);
      }
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public nl.daanh.hiromi.models.proto.Message.Mention.Builder addMentionsBuilder() {
      return getMentionsFieldBuilder().addBuilder(
              nl.daanh.hiromi.models.proto.Message.Mention.getDefaultInstance());
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public nl.daanh.hiromi.models.proto.Message.Mention.Builder addMentionsBuilder(
            int index) {
      return getMentionsFieldBuilder().addBuilder(
              index, nl.daanh.hiromi.models.proto.Message.Mention.getDefaultInstance());
    }

    /**
     * <code>repeated .nl.daanh.hiromi.models.proto.Message.Mention mentions = 6;</code>
     */
    public java.util.List<nl.daanh.hiromi.models.proto.Message.Mention.Builder>
    getMentionsBuilderList() {
      return getMentionsFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            nl.daanh.hiromi.models.proto.Message.Mention, nl.daanh.hiromi.models.proto.Message.Mention.Builder, nl.daanh.hiromi.models.proto.Message.MentionOrBuilder>
    getMentionsFieldBuilder() {
      if (mentionsBuilder_ == null) {
        mentionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                nl.daanh.hiromi.models.proto.Message.Mention, nl.daanh.hiromi.models.proto.Message.Mention.Builder, nl.daanh.hiromi.models.proto.Message.MentionOrBuilder>(
                mentions_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        mentions_ = null;
      }
      return mentionsBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nl.daanh.hiromi.models.proto.Message)
  }

  // @@protoc_insertion_point(class_scope:nl.daanh.hiromi.models.proto.Message)
  private static final nl.daanh.hiromi.models.proto.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new nl.daanh.hiromi.models.proto.Message();
  }

  public static nl.daanh.hiromi.models.proto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public nl.daanh.hiromi.models.proto.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

