// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: guildmessage.proto

package nl.daanh.hiromi.models.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nl.daanh.hiromi.models.proto.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string username = 1;</code>
   * @return Whether the username field is set.
   */
  boolean hasUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>optional string guild_id = 2;</code>
   * @return Whether the guildId field is set.
   */
  boolean hasGuildId();
  /**
   * <code>optional string guild_id = 2;</code>
   * @return The guildId.
   */
  java.lang.String getGuildId();
  /**
   * <code>optional string guild_id = 2;</code>
   * @return The bytes for guildId.
   */
  com.google.protobuf.ByteString
      getGuildIdBytes();

  /**
   * <code>optional string channel_id = 3;</code>
   * @return Whether the channelId field is set.
   */
  boolean hasChannelId();
  /**
   * <code>optional string channel_id = 3;</code>
   * @return The channelId.
   */
  java.lang.String getChannelId();
  /**
   * <code>optional string channel_id = 3;</code>
   * @return The bytes for channelId.
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <code>optional string user_id = 4;</code>
   * @return Whether the userId field is set.
   */
  boolean hasUserId();
  /**
   * <code>optional string user_id = 4;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>optional string user_id = 4;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>optional string message = 5;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>optional string message = 5;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 5;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
