package nl.daanh.hiromi.listeners;

import net.dv8tion.jda.api.events.interaction.ButtonClickEvent;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import nl.daanh.hiromi.CommandManager;
import org.jetbrains.annotations.NotNull;

public class ButtonClickListener extends ListenerAdapter {
    private final CommandManager commandManager;

    public ButtonClickListener(CommandManager commandManager) {
        this.commandManager = commandManager;
    }

    @Override
    public void onButtonClick(@NotNull ButtonClickEvent event) {
        if (event.getUser().isBot()) return;

        // TODO Prevent spoofing with some sort of cache key?
        // users can spoof this id so be careful what you do with this
        String[] data = event.getComponentId().split(":"); // this is the custom id we specified in our button
        if (data.length < 3) return;
        String authorId = data[0];

        // When storing state like this is it is highly recommended to do some kind of verification that it was generated by you, for instance a signature or local cache
        if (!authorId.equals(event.getUser().getId()))
            return;

        this.commandManager.handle(event, data);
    }
}
